version: "3.9"
services:
  # NGINX Proxy Manager (https://github.com/NginxProxyManager/nginx-proxy-manager)
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: angannondir-npm
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      DB_MYSQL_HOST: "mysql"
      DB_MYSQL_NAME: ${ANGANNONDIR_NPM_DATABASE:-npm}
      DB_MYSQL_PASSWORD: ${ROOT_PASSWORD:-npm}
      DB_MYSQL_PORT: ${MYSQL_PORT:-3306}
      DB_MYSQL_USER: ${ROOT_USERNAME:-npm}
      DISABLE_IPV6: "TRUE"
    networks:
      - gulhir
    ports:
      - ${ANGANNONDIR_NPM_PORT_HTTP:-80}:80
      - ${ANGANNONDIR_NPM_PORT_HTTPS:-443}:443
      - ${ANGANNONDIR_NPM_PORT_ADMIN:-81}:81
    restart: always
    volumes:
      - ${ANGANNONDIR_NPM_PATH:-./npm}/app:/data
      - ${ANGANNONDIR_NPM_PATH:-./npm}/letsencrypt:/etc/letsencrypt
    depends_on:
      - mysql
    deploy:
      labels:
        - homepage.instance.admin.description=Reverse proxy manager
        - homepage.instance.admin.href=${ANGANNONDIR_NPM_URL:-http://localhost}
        - homepage.instance.admin.icon=nginx-proxy-manager.svg
        - homepage.instance.admin.group=Angannond√≠r
        - homepage.instance.admin.name=NGINX Proxy Manager
        - homepage.instance.admin.widget.type=npm
        - homepage.instance.admin.widget.url=${RAEDORVUDH_IP:-http://localhost}:${ANGANNONDIR_NPM_PORT_ADMIN:-81}
        - homepage.instance.admin.widget.username=${ANGANNONDIR_NPM_USERNAME:-changeMe}
        - homepage.instance.admin.widget.password=${ANGANNONDIR_NPM_PASSWORD:-changeMe}
        - homepage.instance.admin.widget.fields=["enabled", "disabled", "total"]
      placement:
        constraints: [node.labels.angannondir == true]

  # Cloudflare (https://github.com/favonia/cloudflare-ddns)
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: angannondir-cloudflare
    cap_drop:
      - all
    environment:
      CF_API_TOKEN: ${ANGANNONDIR_CLOUDFLARE_TOKEN:-changeMe}
      DOMAINS: ${DOMAINS:-changeMe.biz}
      IP6_PROVIDER: "none"
      PROXIED: "TRUE"
      TZ: ${TZ:-America/Los_Angeles}
    network_mode: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: "${PUID:-1000}:${PGID:-1000}"
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]

  # DuckDNS (https://github.com/linuxserver/docker-duckdns)
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: angannondir-duckdns
    environment:
      LOG_FILE: "FALSE"
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      SUBDOMAINS: ${ANGANNONDIR_DUCKDNS_SUBDOMAIN:-changeMe.biz}
      TOKEN: ${ANGANNONDIR_DUCKDNS_TOKEN:-changeMe}
      TZ: ${TZ:-America/Los_Angeles}
    restart: unless-stopped
    volumes:
      - ${ANGANNONDIR_DUCKDNS_PATH:-./duckdns}:/config
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]

networks:
  gulhir:
    external: true
