version: "3.9"
services:
  # Homepage (https://gethomepage.dev/)
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: lochuil-homepage
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      HOMEPAGE_ALLOWED_HOSTS: "*"
    networks:
      - gulhir
    ports:
      - ${LOCHUIL_HOMEPAGE_PORT:-3000}:3000
    restart: unless-stopped
    volumes:
      - ${LOCHUIL_HOMEPAGE_PATH:-./homepage}:/app/config
      - ${LOCHUIL_HOMEPAGE_PATH:-./homepage}/icons:/app/public/icons
      - ${LOCHUIL_HOMEPAGE_PATH:-./homepage}/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.hostname == nadhrawlos]

  # Homepage Admin (https://gethomepage.dev/)
  homepage_admin:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: lochuil-homepage-admin
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      HOMEPAGE_ALLOWED_HOSTS: "*"
    networks:
      - gulhir
    ports:
      - ${LOCHUIL_HOMEPAGE_ADMIN_PORT:-3000}:3000
    restart: unless-stopped
    volumes:
      - ${LOCHUIL_HOMEPAGE_ADMIN_PATH:-./homepage}:/app/config
      - ${LOCHUIL_HOMEPAGE_ADMIN_PATH:-./homepage}/icons:/app/public/icons
      - ${LOCHUIL_HOMEPAGE_ADMIN_PATH:-./homepage}/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.hostname == nadhrawlos]

networks:
  gulhir:
    external: true

volumes:
  thinmbahad-photos-public:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/94.Photos/94.01.Public
