version: "3.9"
services:
  # Manyfold (https://manyfold.app)
  manyfold:
    image: ghcr.io/manyfold3d/manyfold:latest
    container_name: tolodbothur-manyfold
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    environment:
      PUID: ${PUID_NAS:-1000}
      PGID: ${PGID_NAS:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}/${REDIS_DB_MANYFOLD:-0}
      SECRET_KEY_BASE: ${TOLODBOTHUR_MANYFOLD_SECRET:-changeMe}
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: postgres
      DATABASE_PORT: ${POSGRES_PORT:-5432}
      DATABASE_USER: ${ROOT_USERNAME:-changeMe}
      DATABASE_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      DATABASE_NAME: ${TOLODBOTHUR_MANYFOLD_DATABASE_NAME:-manyfold}
    networks:
      - gulhir
    ports:
      - ${TOLODBOTHUR_MANYFOLD_PORT:-3214}:3214
    restart: unless-stopped
    volumes:
      - ${TOLODBOTHUR_MANYFOLD_PATH:-./manyfold}:/config
      - gogiwnadh-models:/libraries
    depends_on:
      - redis
      - postgres
    deploy:
      labels:
        - homepage.instance.admin.group=Tolodbothur
        - homepage.instance.admin.name=Manyfold
        - homepage.instance.admin.description=3D model manager
        - homepage.instance.admin.icon=sh-manyfold
        - homepage.instance.admin.href=${TOLODBOTHUR_MANYFOLD_URL:-http://localhost}
      placement:
        constraints: [node.hostname == budhdun]

networks:
  gulhir:
    external: true

volumes:
  gogiwnadh-models:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${GOGIWNADH_PATH}/78.Models
